# Generated by Django 5.2.11 on 2026-02-24 20:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', editable=False, max_length=24, unique=True)),
                ('content', models.JSONField(blank=True, default=api.models.default_frontend_content)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frontend Settings',
                'verbose_name_plural': 'Frontend Settings',
            },
        ),
    ]
