# Generated by Codex on 2026-02-25.
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def forwards_populate_order_data(apps, schema_editor):
    Order = apps.get_model("api", "Order")
    OrderItem = apps.get_model("api", "OrderItem")
    AdminNotification = apps.get_model("api", "AdminNotification")

    used_numbers = set(
        value
        for value in Order.objects.exclude(order_number__isnull=True).values_list("order_number", flat=True)
        if value
    )

    for order in Order.objects.all().select_related("customer"):
        if order.status == "paid":
            order.status = "completed"
        if not order.order_number:
            candidate = f"CC-{uuid.uuid4().hex[:8].upper()}"
            while candidate in used_numbers:
                candidate = f"CC-{uuid.uuid4().hex[:8].upper()}"
            order.order_number = candidate
            used_numbers.add(candidate)

        if order.customer and not order.customer_name:
            full_name = f"{order.customer.first_name} {order.customer.last_name}".strip()
            order.customer_name = full_name or order.customer.username or order.customer.email

        if order.total_amount is None:
            order.total_amount = Decimal("0.00")

        order.save(update_fields=["status", "order_number", "customer_name", "total_amount", "updated_at"])

    for item in OrderItem.objects.select_related("menu_item").all():
        if not item.item_name and item.menu_item:
            item.item_name = item.menu_item.name
        if item.item_price is None or item.item_price == 0:
            item.item_price = item.unit_price or Decimal("0.00")
        if item.unit_price is None or item.unit_price == 0:
            item.unit_price = item.item_price or Decimal("0.00")

        subtotal = item.line_total or (item.item_price * item.quantity)
        item.subtotal = subtotal
        item.line_total = subtotal
        item.save(update_fields=["item_name", "item_price", "unit_price", "subtotal", "line_total"])

    for notification in AdminNotification.objects.all():
        lowered_title = (notification.title or "").lower()
        if "order" in lowered_title:
            notification.notif_type = "new_order"
            notification.save(update_fields=["notif_type"])


def backwards_noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_seed_frontendsettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="email",
            new_name="customer_email",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name="order_items", to="api.menuitem"),
        ),
        migrations.AddField(
            model_name="adminnotification",
            name="notif_type",
            field=models.CharField(
                choices=[("new_order", "New Order"), ("status_update", "Status Update"), ("general", "General")],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="adminnotification",
            name="recipient",
            field=models.ForeignKey(on_delete=models.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chef", "Chef"),
                            ("waiter", "Waiter / Waitress"),
                            ("cashier", "Cashier"),
                            ("manager", "Manager"),
                            ("cleaner", "Cleaning Staff"),
                            ("security", "Security"),
                            ("delivery", "Delivery"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="staff/")),
                ("bio", models.TextField(blank=True)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_on_website", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("role", "full_name")},
        ),
        migrations.RunPython(forwards_populate_order_data, backwards_noop),
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
