# Generated by Django 5.2.11 on 2026-02-25 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_notification_staffmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='api_order_user_id_0b6717_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status', 'created_at'], name='api_order_custome_dc93cd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='api_order_order_n_ec9cdb_idx'),
        ),
    ]
