# Generated by Django 5.2.12 on 2026-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_table_reservation_party_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='link_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notif_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('status_update', 'Status Update'), ('audit', 'Audit'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
