# Generated by Codex on 2026-02-25

from django.conf import settings
from django.db import migrations


def _customer_name(user):
    full_name = f"{getattr(user, 'first_name', '')} {getattr(user, 'last_name', '')}".strip()
    if full_name:
        return full_name
    username = getattr(user, "username", "")
    if username:
        return username
    email = getattr(user, "email", "")
    return email or "Guest"


def backfill_order_customer_fields(apps, schema_editor):
    order_model = apps.get_model("api", "Order")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(user_app_label, user_model_name)

    for order in order_model.objects.select_related("customer").all():
        changed = []

        if order.customer_id:
            customer = order.customer
        else:
            customer = None
            if order.customer_email:
                customer = user_model.objects.filter(email__iexact=order.customer_email).first()
                if customer:
                    order.customer_id = customer.pk
                    changed.append("customer")

        if customer and not order.customer_name:
            order.customer_name = _customer_name(customer)
            changed.append("customer_name")

        if customer and not order.customer_email:
            order.customer_email = getattr(customer, "email", "") or ""
            changed.append("customer_email")

        if changed:
            changed.append("updated_at")
            order.save(update_fields=changed)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_order_api_order_user_id_0b6717_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_order_customer_fields, noop_reverse),
    ]

