# Generated by Django 5.2.12 on 2026-03-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_assigned_chef_userprofile_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='api.reservation'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notif_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('status_update', 'Status Update'), ('reservation', 'New Reservation'), ('audit', 'Audit'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
