# Generated by Django 5.2 on 2026-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adminnotification_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('chef', 'Chef'), ('waiter', 'Waiter / Waitress'), ('cashier', 'Cashier'), ('cleaner', 'Cleaning Staff'), ('security', 'Security'), ('delivery', 'Delivery'), ('other', 'Other'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
