"""Seed menu items based on the provided City Cafe menu sheets."""
from decimal import Decimal

from django.core.management.base import BaseCommand

from api.models import MenuItem


class Command(BaseCommand):
    """Populate database with production-style menu items."""

    help = "Seed menu items from the current restaurant menu."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete menu items not present in this seed list before seeding.",
        )

    def handle(self, *args, **options):
        items = [
            # Snacks
            {
                "name": "Plain Chapati",
                "description": "Fresh plain chapati snack.",
                "price": Decimal("2000.00"),
                "category": MenuItem.Category.STARTERS,
                "image_url": "",
                "is_available": True,
                "is_featured": True,
                "dietary_tags": [],
            },
            {
                "name": "Chapati with Eggs (2)",
                "description": "Chapati served with two eggs.",
                "price": Decimal("3500.00"),
                "category": MenuItem.Category.STARTERS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Chapati with Egg (1)",
                "description": "Chapati served with one egg.",
                "price": Decimal("3000.00"),
                "category": MenuItem.Category.STARTERS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Chapati with Beef or Chicken Stir Fry",
                "description": "Chapati with beef or chicken stir fry filling.",
                "price": Decimal("8000.00"),
                "category": MenuItem.Category.STARTERS,
                "image_url": "",
                "is_available": True,
                "is_featured": True,
                "dietary_tags": [],
            },
            {
                "name": "Chicken Wrap",
                "description": "Chicken wrap snack option.",
                "price": Decimal("10000.00"),
                "category": MenuItem.Category.STARTERS,
                "image_url": "",
                "is_available": True,
                "is_featured": True,
                "dietary_tags": [],
            },
            {
                "name": "Samoosa",
                "description": "Crispy samoosa.",
                "price": Decimal("2500.00"),
                "category": MenuItem.Category.STARTERS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Doughnuts",
                "description": "Sweet doughnut snack.",
                "price": Decimal("1500.00"),
                "category": MenuItem.Category.STARTERS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            # Beverages
            {
                "name": "Soft Drink (Glass Bottle)",
                "description": "Soft drink served in a glass bottle.",
                "price": Decimal("1500.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Soft Drink (Plastic Bottle)",
                "description": "Soft drink served in a plastic bottle.",
                "price": Decimal("1800.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Water",
                "description": "Bottled water.",
                "price": Decimal("1000.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Black Tea",
                "description": "Classic black tea.",
                "price": Decimal("2500.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Milk",
                "description": "Fresh milk drink.",
                "price": Decimal("3500.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Hot Chocolate",
                "description": "Hot chocolate beverage.",
                "price": Decimal("4500.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Roibos",
                "description": "Rooibos tea beverage.",
                "price": Decimal("3500.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Coffee",
                "description": "Fresh coffee.",
                "price": Decimal("4500.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Extra Milk",
                "description": "Extra milk add-on.",
                "price": Decimal("1000.00"),
                "category": MenuItem.Category.DRINKS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Ice-Cream Cone",
                "description": "Ice-cream served in a cone.",
                "price": Decimal("5000.00"),
                "category": MenuItem.Category.DESSERTS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegetarian"],
            },
            {
                "name": "Ice-Cream Cup",
                "description": "Ice-cream served in a cup.",
                "price": Decimal("6000.00"),
                "category": MenuItem.Category.DESSERTS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegetarian"],
            },
            # Mains: Served with starch on offer
            {
                "name": "Eggs (2) with Starch",
                "description": "Two eggs served with starch on offer.",
                "price": Decimal("7000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Beef Stew/Fried/Boiled",
                "description": "Beef served as stew, fried, or boiled with starch.",
                "price": Decimal("8000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": True,
                "dietary_tags": [],
            },
            {
                "name": "Goat Stew/Fried/Boiled",
                "description": "Goat served as stew, fried, or boiled with starch.",
                "price": Decimal("8000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": True,
                "dietary_tags": [],
            },
            {
                "name": "Local Chicken Stew/Fried/Boiled",
                "description": "Local chicken served as stew, fried, or boiled with starch.",
                "price": Decimal("9000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": True,
                "dietary_tags": [],
            },
            {
                "name": "Hybrid Fried Chicken Piece",
                "description": "Single hybrid fried chicken piece with starch.",
                "price": Decimal("8500.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Hybrid Braii 1/4 Chicken",
                "description": "Quarter hybrid braai chicken with starch.",
                "price": Decimal("13000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Fried Open Chambo Medium",
                "description": "Medium fried open chambo fish.",
                "price": Decimal("17800.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": True,
                "dietary_tags": [],
            },
            {
                "name": "Fried Open Chambo Large",
                "description": "Large fried open chambo fish.",
                "price": Decimal("25000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Smoked Butterfish Medium",
                "description": "Medium smoked butterfish.",
                "price": Decimal("25000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Smoked Butterfish Large",
                "description": "Large smoked butterfish.",
                "price": Decimal("30000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Goat Soup",
                "description": "Rich goat soup.",
                "price": Decimal("10000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Goat Khwasukhwasu",
                "description": "Traditional goat khwasukhwasu.",
                "price": Decimal("10000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            # Mains: Served with nsima or rice
            {
                "name": "Beans with Nsima or Rice",
                "description": "Beans served with nsima or rice.",
                "price": Decimal("6000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegetarian"],
            },
            {
                "name": "Masamba Otendera",
                "description": "Masamba otendera served with nsima or rice.",
                "price": Decimal("5500.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegetarian"],
            },
            {
                "name": "Special Veggies",
                "description": "Special vegetables served with nsima or rice.",
                "price": Decimal("6000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegetarian"],
            },
            # Mains: Extra relish
            {
                "name": "Extra Relish - Beef/Goat",
                "description": "Extra relish of beef or goat.",
                "price": Decimal("7000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Extra Relish - Hybrid Fried Chicken",
                "description": "Extra relish with hybrid fried chicken.",
                "price": Decimal("7000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Extra Relish - Local Chicken",
                "description": "Extra relish with local chicken.",
                "price": Decimal("10000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Extra Relish - Eggs",
                "description": "Extra relish with eggs.",
                "price": Decimal("7000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Extra Relish - Hybrid Braii 1/4 Chicken",
                "description": "Extra relish with quarter hybrid braai chicken.",
                "price": Decimal("13000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Extra Relish - Goat Soup",
                "description": "Extra relish goat soup.",
                "price": Decimal("10000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            {
                "name": "Extra Relish - Goat Khwasukhwasu",
                "description": "Extra relish goat khwasukhwasu.",
                "price": Decimal("10000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": [],
            },
            # Mains: Starch only
            {
                "name": "Nsima (Piece)",
                "description": "Single piece of nsima.",
                "price": Decimal("1000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegan"],
            },
            {
                "name": "Rice",
                "description": "Portion of rice.",
                "price": Decimal("1000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegan"],
            },
            {
                "name": "Chips",
                "description": "Portion of chips.",
                "price": Decimal("6000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegan"],
            },
            {
                "name": "Boiled Irish",
                "description": "Boiled Irish potatoes.",
                "price": Decimal("6000.00"),
                "category": MenuItem.Category.MAINS,
                "image_url": "",
                "is_available": True,
                "is_featured": False,
                "dietary_tags": ["vegan"],
            },
        ]

        seeded_names = [item["name"] for item in items]

        if options.get("reset"):
            MenuItem.objects.exclude(name__in=seeded_names).delete()

        created_count = 0
        updated_count = 0

        for item in items:
            _, created = MenuItem.objects.update_or_create(
                name=item["name"],
                defaults=item,
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seed complete. Created {created_count} menu items, updated {updated_count}."
            )
        )
